name       : focuswriter
version    : 1.8.0
release    : 32
source     :
    - https://github.com/gottcode/focuswriter/archive/v1.8.0.tar.gz : dea9b71f3650134a8fe15e4d812b9d55f01c581ee51ad9c51a06394218b064b1
homepage   : https://gottcode.org/focuswriter/
license    : GPL-3.0-or-later
component  : office
summary    : Simple, distraction-free word processor
description: |
    FocusWriter is a simple, distraction-free word processor. It utilizes a hide-away interface that you access by moving your mouse to the edges of the screen, allowing the program to have a familiar look and feel to it while still getting out of the way so that you can immerse yourself in your work. FocusWriter allows you to customize your environment by creating themes that control the font, colors, and background image to add ambiance. It also features on-the-fly updating statistics, daily goals, multiple open documents, spell-checking, and much more. Additionally, when you open the program your current work in progress will automatically load and position you where you last left off so that you can immediately jump back in.
builddeps  :
    - pkgconfig(Qt6Core5Compat)
    - pkgconfig(Qt6Help)
    - pkgconfig(Qt6Multimedia)
    - pkgconfig(hunspell)
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install # INSTALL_ROOT=$installdir
