name    : focuswriter
version : 1.5.3
release : 1
homepage: http://gottcode.org/focuswriter/
source :
 - https://github.com/gottcode/focuswriter/archive/v1.5.3.zip : e44a227b943a7ca5ebe7f1d3312180a299bc0a224de0be0cf41ac5e9b9174cd9
license : GPL-3.0
summary : FocusWriter
builddeps :
    - qt5-devel
    - pkgconfig(glesv2)
    - pkgconfig(hunspell)
description : FocusWriter is a simple, distraction-free word processor.
setup : |
    qmake PREFIX=$installdir/usr
build : |
    %make
install : |
    %make_install

