name       : focuswriter
version    : 1.7.6
release    : 30
homepage   : https://gottcode.org/focuswriter/
source     :
    - https://github.com/gottcode/focuswriter/archive/v1.7.6.tar.gz : bbf70def7d86ee18cabe9f8ac3922ebbf4dfdb36893df3e6fa3e026acfcb2057
license    : GPL-3.0-or-later
component  : office
summary    : Simple, distraction-free word processor.
description: |
    FocusWriter is a simple, distraction-free word processor. It utilizes a hide-away interface that you access by moving your mouse to the edges of the screen, allowing the program to have a familiar look and feel to it while still getting out of the way so that you can immerse yourself in your work. FocusWriter allows you to customize your environment by creating themes that control the font, colors, and background image to add ambiance. It also features on-the-fly updating statistics, daily goals, multiple open documents, spell-checking, and much more. Additionally, when you open the program your current work in progress will automatically load and position you where you last left off so that you can immediately jump back in.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(libpulse)
    - pkgconfig(hunspell)
setup      : |
    %qmake PREFIX=$installdir/usr
build      : |
    %make
install    : |
    %make_install
